### ISSUE TITLE
Player stuck in goo blocks displays 'Fall' animation

### ISSUE THREAD

**Issue by Sukasa** [Sukasa/16pxGame#5]
In the new player-animation code written by @Tiogshi it appears that when the player falls into Goo blocks that they get stuck showing the 'fall' animation instead of the standard walking or stand-still animation.

**Comment by Tiogshi** [comment]
Just need to add an appropriate check to [this line](https://github.com/Sukasa/16pxGame/blob/master/Code/Mobs/Player.dm#L140). At this moment, I'm not sure how to detect Goo, though.
